<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="bc51d3fd-2ec3-4ee1-a437-adf60d4704e0" name="gudmundssonm@WMLI032191 2012-05-15 13:53:36" runUser="GROUPINFRA\gudmundssonm" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="86cf49bf-788a-4610-b4e9-4251082e7a36">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="gudmundssonm_WMLI032191 2012-05-15 13_53_36">
      <DeploymentItem filename="c:\dotnet\ep.cs\ep.cs\bin\Debug\ep.cs.exe" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-05-15T13:53:36.1416157+02:00" queuing="2012-05-15T13:53:36.4656326+02:00" start="2012-05-15T13:53:36.4956343+02:00" finish="2012-05-15T13:53:36.9726616+02:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="ShouldNotBeAbleToOpenconnectonTwice" storage="c:\dotnet\ep.cs\testconnection\bin\debug\testconnection.dll" id="3115ed26-5e48-9c36-7327-9228485c3d9f">
      <Execution id="4a23a66f-0b13-4872-9e93-02009ee73b81" />
      <TestMethod codeBase="c:/dotnet/ep.cs/TestConnection/bin/Debug/TestConnection.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestConnection.UnitTest1, TestConnection, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="ShouldNotBeAbleToOpenconnectonTwice" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="3115ed26-5e48-9c36-7327-9228485c3d9f" executionId="4a23a66f-0b13-4872-9e93-02009ee73b81" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="4a23a66f-0b13-4872-9e93-02009ee73b81" testId="3115ed26-5e48-9c36-7327-9228485c3d9f" testName="ShouldNotBeAbleToOpenconnectonTwice" computerName="WMLI032191" duration="00:00:00.0758948" startTime="2012-05-15T13:53:36.5026347+02:00" endTime="2012-05-15T13:53:36.9516604+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="4a23a66f-0b13-4872-9e93-02009ee73b81">
      <Output>
        <ErrorInfo>
          <Message>Test method TestConnection.UnitTest1.ShouldNotBeAbleToOpenconnectonTwice did not throw expected exception exercise.ConnectionIsOpenException.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>